In [60]:
#Import necessary libraries
import pandas as pd

df = pd.read_csv("Advertising.csv")

df = df.iloc[:,1:len(df)]

df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [61]:
X = df.drop("Sales", axis=1)

y = df[["Sales"]]

In [62]:
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [63]:
y.head()

Sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [64]:
import statsmodels.api as sm

In [65]:
lm = sm.OLS(y, X)

In [66]:
model = lm.fit()

In [67]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  Sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Mon, 23 Sep 2024   Prob (F-statistic):                   2.43e-171
Time:                        16:17:35   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
Radio          0.2222      0.009     23.595      0.000       0.204       0.241
Newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [68]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()

In [69]:
lm.fit(X,y)

LinearRegression()

In [70]:
lm.intercept_

array([2.93888937])

In [71]:
lm.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

In [72]:
new_data = [[30], [10], [40]]

new_data = pd.DataFrame(new_data).T

In [73]:
new_data

0   1   2
0  30  10  40

In [74]:
lm.predict(new_data)

c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [75]:
from sklearn.metrics import mean_squared_error

In [76]:
predicted = model.predict(X)[0:10]

In [77]:
MSE = mean_squared_error(y[0:10], predicted)
MSE

6.22111933140745

In [78]:
import numpy as np

RMSE = np.sqrt(MSE)
RMSE

2.494217178075608

In [79]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 1)

In [80]:
lm = LinearRegression()

In [81]:
model = lm.fit(X_train,y_train)

In [82]:
#Train error
RMSE = np.sqrt(mean_squared_error(y_train, model.predict(X_train)))
RMSE

1.736902590147092

In [83]:
#Test error
RMSE = np.sqrt(mean_squared_error(y_test,model.predict(X_test)))
RMSE

1.4113417558581585

In [84]:
#K-fold cross-validation
from sklearn.model_selection import cross_val_score

cross_mse = np.mean(-cross_val_score(model, X_train, y_train, cv = 10, scoring = "neg_mean_squared_error"))
cross_mse

3.187711520944357

In [85]:
cross_rmse = np.sqrt(cross_mse)
cross_rmse

1.7854163438661463