In [1]:
#Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso , ElasticNet
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.model_selection import train_test_split,cross
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV

ImportError: cannot import name 'cross_val_score' from 'sklearn.metrics' (c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\metrics\__init__.py)

In [2]:
df = pd.read_csv("Hitters.csv")

df = df.dropna()

dms = pd.get_dummies(df[["League", "Division", "NewLeague"]])

y = df["Salary"]

X_ = df.drop(["Salary", "League", "Division", "NewLeague"], axis=1).astype("float64")

X = pd.concat([X_, dms[["League_N", "Division_W", "NewLeague_N"]]], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=42)

In [3]:
enet_model = ElasticNet().fit(X_train,y_train)

c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [4]:
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [5]:
enet_model.intercept_

-6.465955602114036

In [8]:
enet_model.predict(X_train)[0:10]

array([325.74706292, 776.06632333, 522.86508419, 107.64091955,
       449.03139566, 997.76095723,  99.78828622, 311.33763086,
       418.50335021, 879.9502608 ])

In [9]:
enet_model.predict(X_test)[0:10]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123])

In [10]:
y_pred = enet_model.predict(X_test)

In [12]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
rmse

357.1676548181248

In [13]:
r2_score(y_test,y_pred)

0.410702224693268

In [33]:
alphas = 10**np.linspace(10,-2,100)*0.5
l1_ratios = np.linspace(0,1,11)
l1_ratios

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [34]:
enet_cv = ElasticNetCV(alphas=alphas,l1_ratio=l1_ratios,cv=10).fit(X_train,y_train)

c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:664: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:664: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 16200598.55448147, tolerance: 3241.4244490642723
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:664: UserWarning: Coordinate descent without L1 regularization may lead to unexpected results and is discouraged. Set l1_ratio > 0 to add L1 regularization.
  model = cd_fast.enet_coordinate_descent_gram(
c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:664: ConvergenceWarning: O

In [25]:
enet_cv.alpha_

5748.784976988678

In [37]:
enet_cv.l1_ratio_

0.0

In [26]:
enet_cv.coef_

array([ 0.61111381,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.11212622,  0.        ,
        0.25252702,  0.18656722,  0.00444355,  0.30988823,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [27]:
enet_cv.intercept_

-31.46312122564109

In [38]:
enet_tuned = ElasticNet(alpha=enet_cv.alpha_,l1_ratio=enet_cv.l1_ratio_).fit(X_train,y_train)

c:\Users\omerf\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.036e+07, tolerance: 3.899e+03 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(


In [39]:
y_pred = enet_tuned.predict(X_test)

In [40]:
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
rmse

385.736910766154